#
# This is a conda build config file.
#
# For details on these settings, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
#
# To use this file in conjunction with the 'publish-conda-stack' tool,
# your specs file should start with these lines:
#
#   shared-config:
#     master-conda-build-config: master-conda-build-config.yaml
#
# In general, we should try to keep this in-sync with conda-forge's master build config:
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

boost:
  - 1.82.0
boost_cpp:
  - 1.82.0
hdf5:
  - 1.14.3
jsoncpp:
  - 1.9.5
librdkafka:
  - '2.2'
lz4:
  - 4
lz4_c:
  - 1.9.3
numpy:
  #- 1.21  # For python 3.10
  #- 1.22.0  # For python 3.10
  #- 1.23  # Earliest numpy for py3.11
  - 1.26
python:
  #- 3.10.* *_cpython
  #- 3.11.* *_cpython
  - 3.12.* *_cpython
python_impl:
  - cpython
zeromq:
  - 4.3.5

# Notes:
# py310/np1.21.6: pass

# py310/np1.22.0: fail (required setting test env to np1.22.0)
# py310/np1.22.4: fail

# py310/np1.23: fail

# py311/np1.23: fail
# py312/np1.26: fail (with newer xtensor, but that probably doesn't matter)


# conda-forge uses these zip_keys, so we do it here even though
# it's not necessary since we only use a single version of each.
zip_keys:
  -
    - python
    - numpy
    - python_impl

pin_run_as_build:
  boost:
    max_pin: x.x.x
  boost_cpp:
    max_pin: x.x.x
  hdf5:
    max_pin: x.x.x
  jsoncpp:
    max_pin: x.x.x
  librdkafka:
    max_pin: x.x.x
  lz4:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    max_pin: x.x
  zeromq:
    max_pin: x.x

CONDA_BUILD_SYSROOT:
  # Most conda-forge packages are compatible with MacOSX 10.9,
  # but golang-1.16 requires at least MacOSX 10.13.
  # (See the download page: https://go.dev/dl/)
  #
  # The simplest thing to do is to download the SDK from the release page in this repo:
  # https://github.com/phracker/MacOSX-SDKs
  # https://github.com/phracker/MacOSX-SDKs/releases
  #
  # Previously, we would use the XcodeLegacy script, via the following project,
  # but it doesn't seem to work with new versions of Xcode.
  # https://github.com/devernay/xcodelegacy

  #- /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

# MACOSX_DEPLOYMENT_TARGET:
#   - 10.13

