#
# This is a conda build config file.
#
# For details on these settings, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
#
# To use this file in conjunction with the 'publish-conda-stack' tool,
# your specs file should start with these lines:
#
#   shared-config:
#     master-conda-build-config: master-conda-build-config.yaml
#
# In general, we should try to keep this in-sync with conda-forge's master build config:
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

boost:
  - 1.78.0
boost_cpp:
  - 1.78.0
hdf5:
  - 1.12.1
jsoncpp:
  - 1.9.5
librdkafka:
  - '1.9'
lz4:
  - 3
lz4_c:
  - 1.9.3
numpy:
  - 1.21
python:
  - 3.10
python_impl:
  - cpython
zeromq:
  - 4.3.4

pin_run_as_build:
  boost:
    max_pin: x.x.x
  boost_cpp:
    max_pin: x.x.x
  hdf5:
    max_pin: x.x.x
  jsoncpp:
    max_pin: x.x.x
  librdkafka:
    max_pin: x.x.x
  lz4:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  python:
    max_pin: x.x
  zeromq:
    max_pin: x.x

CONDA_BUILD_SYSROOT:
  # Most conda-forge packages are compatible with MacOSX 10.9,
  # but golang-1.16 requires at least MacOSX 10.13.
  # (See the download page: https://go.dev/dl/)
  #
  # You will have to install this SDK manually, via this project:
  #
  #   https://github.com/devernay/xcodelegacy
  #
  # Quick Instructions:
  #
  #   curl https://raw.githubusercontent.com/devernay/xcodelegacy/master/XcodeLegacy.sh > XcodeLegacy.sh
  #   chmod +x XcodeLegacy.sh
  #   sudo ./XcodeLegacy.sh -osx1013 buildpackages
  #   sudo ./XcodeLegacy.sh -osx1013 install
  #
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk

MACOSX_DEPLOYMENT_TARGET:
  - 10.13
