{% set version = "2.1.3" %}
{% set minor_version = ".".join(version.split(".")[:2]) %}

package:
  name: glbinding
  version: {{ version }}

source:
  url: https://github.com/cginternals/glbinding/archive/v{{ version }}.tar.gz
  fn:  glbinding-{{ version }}.tar.gz
  sha256: 21e219a5613c7de3668bea3f9577dc925790aaacfa597d9eb523fee2e6fda85c

build:
  number: 3

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/cginternals/glbinding
  license: MIT
  summary: >
    glbinding is an MIT licensed, cross-platform C++ binding for the OpenGL API.
