{% set version = "1.3.4" %}


# To make a debug build, set this environment variable when invoking conda-build.
# Example:
#
#   CMAKE_BUILD_TYPE=Debug conda build draco
# 

{% set name = "draco" %} # default (release build)

{% if CMAKE_BUILD_TYPE is defined %}
  {% if CMAKE_BUILD_TYPE == "Debug" %}
    {% set name = "draco-debug" %}
  {% endif %}
{% endif %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://github.com/google/draco/archive/{{ version }}.tar.gz
  fn:  draco-{{ version }}.tar.gz
  sha256: 9f369ce924974acf9ab582fe8a9e50d86d54346460b0ac6d3808e3fcf269489c # 1.3.4
  

build:
  number: 3
  
  script_env:
    - CMAKE_BUILD_TYPE

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - draco_encoder -h
    - draco_decoder -h

about:
  home: https://github.com/google/draco
  license: MIT
  summary: >
    Draco is a library for compressing and decompressing 3D geometric meshes and point clouds.
    It is intended to improve the storage and transmission of 3D graphics.
